---
common:

".gitlab-ci.yml":
  delete: true
appveyor.yml:
  delete: true
Gemfile:
  optional:
    ":development":
    - gem: 'toml-rb'
    - gem: github_changelog_generator
spec/default_facts.yml:
  extra_facts:
    pe_server_version: 2019.8.4
    pe_build: 2019.8.4
spec/spec_helper.rb:
  mock_with: ":rspec"
  coverage_report: true
.gitpod.Dockerfile:
  delete: true
.gitpod.yml:
  delete: true
.github/workflows/auto_release.yml:
  unmanaged: true
.github/workflows/spec.yml:
  checks: 'syntax lint metadata_lint check:symlinks check:git_ignore check:dot_underscore check:test_file rubocop'
  unmanaged: true
.github/workflows/release.yml:
  unmanaged: true
.travis.yml:
  delete: true
Rakefile:
  changelog_user: "puppetlabs"
